# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8] # value at index 8

8

In [5]:
arr[1:5] # starting index and ending index

array([1, 2, 3, 4])

In [6]:
arr[0:5] 

array([0, 1, 2, 3, 4])

In [7]:
arr[:6] # everything from the start of the arrary to index 6

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:] # start from everything beyond index 5 i.e. index 5 is not included

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100 # broadcasts the value to the first 5 indexes fof the array

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0, 11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_arr = arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [17]:
slice_of_arr[:] = 99 #means grab everything in the slice

In [18]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [19]:
arr # so at the end of it all, the original array is also mutated, why because slice is a view of the orinal array not a copy of the array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
# if you want a copy you have to explicity refer to it
arr_copy = arr.copy()

In [22]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 455]])

In [23]:
arr_2d

array([[  5,  10,  15],
       [ 20,  25,  30],
       [ 35,  40, 455]])

In [24]:
arr_2d[0][0]

5

In [25]:
arr_2d[0]

array([ 5, 10, 15])

In [26]:
arr_2d[1][1]

25

In [27]:
arr_2d[2, 1] # row, col

40

In [28]:
arr_2d[2][1]

40

In [ ]:
# grabbing from the top right corner i.e. 10, 15 and 25, 30 
# more explanation: :2, grab everything but not including row 2 and for columns 1: grab everything from 1 onwards
arr_2d[:2,1:]

In [29]:
# breakdown
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [30]:
arr = np.arange(1, 11)

In [31]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
bool_arr = arr > 5

In [34]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [36]:
arr[arr > 5] # conditional selection

array([ 6,  7,  8,  9, 10])

In [37]:
arr[arr < 3]

array([1, 2])

In [38]:
arr_2d = np.arange(50).reshape(5, 10)

In [39]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
arr_2d[1:3,3:5] # grabs 13, 14, 23, 24

array([[13, 14],
       [23, 24]])

In [40]:
arr_2d[1:3] # grabs row 1 up to but not including 3

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])