# Numpy Arrays

In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list) # np returns an array, you are casting a normal list into an array using numpy

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_mat) # you numpy you can typecast a list of lists into a 2-D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((2, 3)) # 2 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0, 5, 10) # one dimensional vector of 10 evenly spaced points from 1 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [17]:
np.eye(4) # an identity matrix, it's a 2D square matrix meaning the number of rows is the same as the number of columns

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5) # one dimensional array of random numbers from 0 to 1

array([0.54600703, 0.6046444 , 0.53836351, 0.64109746, 0.59550481])

In [19]:
np.random.rand(5, 5) # returns a 5 by 5 matrix of random numbers 

array([[0.61441224, 0.38466855, 0.25597854, 0.97173898, 0.81794913],
       [0.08175642, 0.96314676, 0.37102372, 0.4780799 , 0.75627771],
       [0.32162821, 0.27289022, 0.4662259 , 0.68005761, 0.86298793],
       [0.7147136 , 0.12113217, 0.96100371, 0.7426607 , 0.03890343],
       [0.03574695, 0.16364852, 0.91449439, 0.78602344, 0.8976478 ]])

In [20]:
np.random.randn(2) # returns two numbers from a standard normal distribution or gaussian distribution

array([-1.25034464, -1.46572517])

In [21]:
np.random.randn(4, 4) # returns a 2D normal distribution

array([[-0.18524891,  0.65603045, -0.57434718, -1.44438011],
       [ 0.54428411, -1.32885823,  0.55233844, -0.07730784],
       [-0.31990929,  0.48411128, -1.4090707 ,  0.28315931],
       [-0.70384001, -0.24062232,  0.69709627, -0.78234445]])

In [22]:
 # returns random integers from a low to a high number with lowest inclusive and highest exclusive
np.random.randint(1, 100)

71

In [23]:
np.random.randint(1, 100, 10)

array([51, 80, 72, 10,  7,  7, 30, 44, 29, 11])

In [25]:
arr1 = np.arange(25)

In [26]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0, 50, 10)

In [28]:
ranarr

array([11, 17,  3, 40, 37,  7,  5,  1, 39, 34])

In [29]:
# gives you a 5  by 5 matrix make sure the total number of elements can fill up all areas eg here arr1 is 25 hence we can easily change it to 5 by 5
# basically rows * columns = number of elements you need to reshape
arr1.reshape(5, 5) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr.max() # minimum value

40

In [32]:
ranarr.min() # maximum value

1

In [33]:
ranarr.argmax() # index location of the maximum value

3

In [34]:
ranarr.argmin() # index location of the minimum value

7

In [36]:
arr1.shape # (25, ) means it's a one dimensional vectorb

(25,)

In [37]:
arr_reshaped = arr1.reshape(5, 5)

In [38]:
arr_reshaped.shape

(5, 5)

In [39]:
arr.dtype # data type of your array

dtype('int32')

In [40]:
from numpy.random import randint  # if you don't want to reference np.random.randint

In [41]:
randint(2, 10)

3